org.gradle.jvmargs=-Xmx256m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.66
curios_version=16.0.0+26.2
mod_id=pastbound
mod_name=Pastbound
mod_license=MIT
mod_version=1.1.2
mod_group_id=dev.pastbound
neogradle.subsystems.decompiler.maxMemory=3g
neogradle.subsystems.decompiler.maxThreads=1
