from pathlib import Path

root = Path(__file__).resolve().parents[1]
p = root / "src/main/java/dev/pastbound/history/TarihiKesifDunyasi.java"
s = p.read_text(encoding="utf-8")
s = s.replace("    private static final int DONEM_OZEL_BITI = 1048576;\n", "    private static final int DONEM_OZEL_BITI = 1048576;\n    private static final int SAHNE_KOY_BITI = 2097152;\n    private static final int SAHNE_MADEN_BITI = 4194304;\n    private static final int SAHNE_ATOLYE_BITI = 8388608;\n    private static final int SAHNE_UZAK_LOKASYON_MASKESI = SAHNE_KOY_BITI | SAHNE_MADEN_BITI | SAHNE_ATOLYE_BITI;\n")
s = s.replace("        goreviKontrolEt(oyuncu);\n    }\n    private static void gercekYurumeyiIzle", "        uzakLokasyonlariIzle(oyuncu);\n        goreviKontrolEt(oyuncu);\n    }\n\n    private static void uzakLokasyonlariIzle(ServerPlayer oyuncu) {\n        CompoundTag veri = ((IEntityExtension) oyuncu).getPersistentData();\n        int maske = veri.getIntOr(SAHNE_GOREV_MASKESI, 0);\n        BlockPos koy = SAHNE_MERKEZI.west(28).north(18);\n        BlockPos maden = SAHNE_MERKEZI.east(28).north(18);\n        BlockPos atolye = SAHNE_MERKEZI.south(28);\n        if ((maske & SAHNE_KOY_BITI) == 0 && oyuncu.distanceToSqr(koy.getX() + 0.5D, koy.getY() + 1.0D, koy.getZ() + 0.5D) <= 100.0D) {\n            maske |= SAHNE_KOY_BITI;\n            oyuncu.sendSystemMessage(Component.translatable(\"message.pastbound.world.village_reached\"));\n        }\n        if ((maske & SAHNE_MADEN_BITI) == 0 && oyuncu.distanceToSqr(maden.getX() + 0.5D, maden.getY() + 1.0D, maden.getZ() + 0.5D) <= 100.0D) {\n            maske |= SAHNE_MADEN_BITI;\n            oyuncu.sendSystemMessage(Component.translatable(\"message.pastbound.world.mine_reached\"));\n        }\n        if ((maske & SAHNE_ATOLYE_BITI) == 0 && oyuncu.distanceToSqr(atolye.getX() + 0.5D, atolye.getY() + 1.0D, atolye.getZ() + 0.5D) <= 100.0D) {\n            maske |= SAHNE_ATOLYE_BITI;\n            oyuncu.sendSystemMessage(Component.translatable(\"message.pastbound.world.build_power\"));\n        }\n        veri.putInt(SAHNE_GOREV_MASKESI, maske);\n    }\n\n    public static boolean uzakAtolyeEtkilesildi(ServerPlayer oyuncu, BlockPos konum) {\n        if (!boyuttaMi(oyuncu)) {\n            return false;\n        }\n        BlockPos atolye = SAHNE_MERKEZI.south(28);\n        if (!konum.closerThan(atolye, 4.0D)) {\n            return false;\n        }\n        BlockState durum = oyuncu.level().getBlockState(konum);\n        if (!durum.is(Blocks.FURNACE) && !durum.is(Blocks.CRAFTING_TABLE) && !durum.is(ModBlocks.HISTORICAL_FORGE.get())) {\n            return false;\n        }\n        CompoundTag veri = ((IEntityExtension) oyuncu).getPersistentData();\n        veri.putInt(SAHNE_GOREV_MASKESI, veri.getIntOr(SAHNE_GOREV_MASKESI, 0) | SAHNE_ATOLYE_BITI);\n        oyuncu.sendSystemMessage(Component.translatable(\"message.pastbound.world.power_active\"));\n        goreviKontrolEt(oyuncu);\n        return true;\n    }\n\n    private static void gercekYurumeyiIzle")
s = s.replace("        boolean hareketTamam = duraklarTamam && durakKonusmalariTamam && durakCihazlariTamam && mesafeTamam;", "        boolean uzakLokasyonlarTamam = (gorevMaskesi & SAHNE_UZAK_LOKASYON_MASKESI) == SAHNE_UZAK_LOKASYON_MASKESI;\n        boolean hareketTamam = duraklarTamam && durakKonusmalariTamam && durakCihazlariTamam && mesafeTamam && uzakLokasyonlarTamam;")
p.write_text(s, encoding="utf-8")

p = root / "src/main/java/dev/pastbound/history/TarihYankilari.java"
s = p.read_text(encoding="utf-8")
needle = "        if (oyuncu instanceof ServerPlayer sunucu && TarihiKesifDunyasi.boyuttaMi(sunucu)) {\n            TarihiKesifDunyasi.donemOzelEylem(sunucu, olay.getPos(), olay.getItemStack());\n"
replacement = "        if (oyuncu instanceof ServerPlayer sunucu && TarihiKesifDunyasi.boyuttaMi(sunucu)) {\n            TarihiKesifDunyasi.donemOzelEylem(sunucu, olay.getPos(), olay.getItemStack());\n            if (TarihiKesifDunyasi.uzakAtolyeEtkilesildi(sunucu, olay.getPos())) {\n                olay.setCanceled(true);\n                return;\n            }\n"
if needle not in s:
    raise SystemExit("event noktasi bulunamadi")
s = s.replace(needle, replacement, 1)
p.write_text(s, encoding="utf-8")
print("scene_locations_connected")
